sonar.projectKey=matricula-universidad-continental
sonar.projectName=Matricula - Universidad Continental
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src/app
sonar.tests=backend/tests,frontend/src/tests,frontend/cypress

sonar.language=py,ts

sonar.python.version=3.14

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.token=sqa_eb57ce621367bec7a1fac0122be459266c4dad07

sonar.exclusions=**/node_modules/**,**/.venv/**,**/dist/**,**/coverage/**,**/htmlcov/**,**/__pycache__/**,**/.pytest_cache/**,**/.angular/**,**/test-results/**,**/frontend/src/app/app.ts,**/frontend/src/app/app.config.ts,**/frontend/src/app/app.config.server.ts,**/frontend/src/app/app.routes.ts,**/frontend/src/app/app.routes.server.ts,**/frontend/src/app/guards/auth.guard.ts,**/frontend/src/app/models/modelos.ts,**/frontend/src/app/*.spec.ts
